//
// Screen.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Screen: Codable, JSONEncodable, Hashable {

    public var title: String?
    public var content: Content?

    public init(title: String? = nil, content: Content? = nil) {
        self.title = title
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case content
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(content, forKey: .content)
    }
}

