/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Content

import com.squareup.moshi.Json

/**
 * 
 *
 * @param title 
 * @param content 
 */

data class Screen (

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "content")
    val content: Content? = null

)

